### ISSUE TITLE
file name mistyped in MaskGenGUI.py?

### ISSUE THREAD

**Issue by bhj02** [g2-bernotas/PS-Plant-Framework#6]
Hi, I am testing the program and today meet another error.

In running script: MaskGenGUI.py

Traceback (most recent call last):
  File "C:\Users\bh-j\Desktop\PSPP\PS-Plant-Framework-master\MaskGenGUI.py", line 41, in <module>
    Ui_MainWindow, QtBaseClass = uic.loadUiType(qtCreatorFile)
  File "C:\Users\bh-j\.conda\envs\PSPP_py3.5\lib\site-packages\PyQt4\uic\__init__.py", line 208, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "C:\Users\bh-j\.conda\envs\PSPP_py3.5\lib\site-packages\PyQt4\uic\Compiler\compiler.py", line 140, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "C:\Users\bh-j\.conda\envs\PSPP_py3.5\lib\site-packages\PyQt4\uic\uiparser.py", line 974, in parse
    document = parse(filename)
  File "C:\Users\bh-j\.conda\envs\PSPP_py3.5\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\bh-j\.conda\envs\PSPP_py3.5\lib\xml\etree\ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'MaskGen2.ui'

---------------------------------
I think 'MaskGen2.ui' meant 'MaskGen.ui' found there.
Thanks. :)

**Comment by g2-bernotas** [comment]
Hi, probably 'MaskGen2.ui' was experimental as I don't have this file myself. Please change the 'MaskGen2.ui' to 'MaskGen.ui'.
